### ISSUE TITLE
Config when latex is not on PATH

### ISSUE THREAD

**Issue by awlayton** [fannheyward/coc-texlab#167] opened 2020-08-24 17:14 UTC
My latex is not visible on my `PATH`, but I configured the full location to `latexmk` in my CocConfig. However I still get an error about "Your Tex distribution cannot be detected". Is this intended? It seems like it should be able to just call the command I gave it...

**Comment by fannheyward** [comment] 2020-08-25 05:34
How do you config your latexmk in CocConfig?

**Comment by awlayton** [comment] 2020-08-25 17:26
I added this to my CocConfig
`"latex.build.executable": "/usr/local/texlive/2019/bin/x86_64-linux/latexmk",`

**Comment by fannheyward** [comment] 2020-08-26 06:57
Can you reproduce this issue with VSCode + https://github.com/latex-lsp/texlab-vscode? Looks like it's a TexLab issue.

**Comment by pfoerster** [comment] 2020-08-31 07:03
For now, you can safely ignore the message about your TeX distribution being not detected. Detecting the TeX distribution is **not** required to build a document. In fact, a TeX distribution in the PATH is only required for the following features:
- Resolving things like `\addbibresource{biblatex-examples.bib}` or `\usepackage{mycustompackage}`, where `mycustompackage.sty` is a local package which you installed or created on your own and is not part of the package index `texlab` ships with
- Rendering math formulas (e. g. when hovering over `\begin{equation}`)

All other features should work without a TeX distribution just fine.
We will convert this error message to a log message with warning level in the next version of `texlab`.

**Closed** 2021-02-04 07:07 UTC
Labels: Can't reproduce
